// src/js/tailwind-theme.js
window.tailwind = window.tailwind || {};

window.tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "tertiary": "#291300",
                "on-primary": "#ffffff",
                "secondary-fixed-dim": "#ffb5a0",
                "secondary": "#ad2c00",
                "on-tertiary": "#ffffff",
                "on-primary-fixed": "#051944",
                "error-container": "#ffdad6",
                "surface-container-high": "#e8e8ea",
                "surface": "#f9f9fb",
                "surface-variant": "#e2e2e4",
                "on-background": "#1a1c1d",
                "on-secondary-fixed": "#3b0900",
                "on-primary-container": "#8393c5",
                "inverse-on-surface": "#f0f0f2",
                "outline-variant": "#c5c6d0",
                "on-surface-variant": "#45464f",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-container": "#bf895b",
                "inverse-primary": "#b5c5f9",
                "surface-dim": "#d9dadc",
                "surface-container": "#eeeef0",
                "secondary-fixed": "#ffdbd1",
                "on-tertiary-fixed-variant": "#663d16",
                "surface-tint": "#4d5d8b",
                "on-secondary-fixed-variant": "#872000",
                "on-secondary-container": "#fffbff",
                "primary-container": "#1a2b56",
                "on-secondary": "#ffffff",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#b5c5f9",
                "primary": "#021541",
                "inverse-surface": "#2f3132",
                "tertiary-container": "#472400",
                "background": "#f9f9fb",
                "surface-bright": "#f9f9fb",
                "on-surface": "#1a1c1d",
                "on-error": "#ffffff",
                "tertiary-fixed": "#ffdcc1",
                "tertiary-fixed-dim": "#f6ba88",
                "on-tertiary-fixed": "#2e1500",
                "primary-fixed": "#dae1ff",
                "on-primary-fixed-variant": "#354572",
                "outline": "#757680",
                "secondary-container": "#d83900",
                "surface-container-low": "#f3f3f5",
                "surface-container-highest": "#e2e2e4",
                "error": "#ba1a1a"
            },
            fontFamily: {
                "headline": ["Newsreader", "serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}